#!/bin/sh

code --install-extension ardenivanov.svelte-intellisense
code --install-extension burkeholland.simple-react-snippets
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-extension-pack
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension golang.go
code --install-extension graphql.vscode-graphql
code --install-extension hars.cppsnippets
code --install-extension hollowtree.vue-snippets
code --install-extension igorming.useful-react-snippets
code --install-extension infeng.vscode-react-typescript
code --install-extension ionutvmi.path-autocomplete
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension jcbuisson.vue
code --install-extension styled-components.vscode-styled-components
code --install-extension karunamurti.haml
code --install-extension kevinrose.vsc-python-indent
code --install-extension magicstack.magicpython
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension njqdev.vscode-python-typehint
code --install-extension octref.vetur
code --install-extension prisma.prisma
code --install-extension rebornix.ruby
code --install-extension rust-lang.rust
code --install-extension sdras.vue-vscode-snippets
code --install-extension serayuzgur.crates
code --install-extension svelte.svelte-vscode
code --install-extension swellaby.rust-pack
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.javascriptsnippets
code --install-extension xabikos.reactsnippets
